---
title: "Resolução da Lista 3 - VED"
---

## Resolução dos exercícios - parte computacional
```{r pkgs}
library(tidyverse)

```


### Exercício 1
```{r ex1}
ex1 <- c(3.4, 2.5, 4.8, 2.9, 3.6, 2.8, 3.3, 5.6, 3.7, 2.8, 4.4, 4.0, 5.2, 3.0, 4.8)

# Grafico de Barras
barplot(ex1)
hist(ex1)

mean(ex1)
median(ex1)

boxplot(ex1)
# Grafico de ramo e folhas
stem(ex1)

```

### Exercicio 2
```{r ex2}
gcontrole <- c( 7, 3, -4, 14, 2, 5, 22, -7, 9, 5)
gtratamento <- c(-6, 5, 9, 4, 4, 12, 37, 5, 3, 3)

# Boxplots

boxplot(gcontrole)
boxplot(gtratamento)

mean(gtratamento)
median(gtratamento)


mean(gcontrole)
median(gcontrole)

library(tidyverse)

p<- ggplot() + geom_boxplot(aes(x = gcontrole))
q <- ggplot() + geom_boxplot(aes(x = gtratamento))

library(gridExtra)

grid.arrange(p,q)

p<- ggplot() + geom_violin(aes(x = gcontrole)) 
q <- ggplot() + geom_violin(aes(x = gtratamento))


```


### Exercicio 3
```{r ex3}
temp20 <- c(2.07, 2.14, 2.22, 2.03, 2.21, 2.03, 2.05, 2.18, 2.09, 2.14)
temp40 <- c(2.52, 2.15, 2.49, 2.03, 2.37, 2.05, 1.99, 2.42, 2.08, 2.42)

# tabela de frequencias
fa <- table(temp20)
fr <- prop.table(temp20)

a <- cbind(temp20, fa,fr)

fa.40 <- table(temp40)
fr.40 <- prop.table(temp40)

b <- cbind(temp40, fa.40,fr.40)
```
```{r}
a
```

```{r}
b
```
### Exercicio 4
```{r}
ex5 <- read_delim("censo.txt", delim = " ")
ex5

```



### Exercicio 5
```{r ex4}
fumantes <- c(69.3, 56.0, 22.1, 47.6, 53.2, 48.1, 52.7, 34.4, 60.2, 43.8, 23.2, 13.8 )
naofumam <- c( 28.6, 25.1, 26.4, 34.9, 29.8, 28.4, 38.5, 30.2, 30.6, 31.8, 41.6, 21.1, 36.0, 37.9, 13.9) 

# Boxplots

#fumantes %>% ggplot() + geom_histogram()

#ggplot(data = fumantes) + geom_histogram()

ggplot() + geom_boxplot(aes(x = fumantes, alpha = 0.5, color = "blue")) + geom_boxplot(aes(x = naofumam , alpha = 0.5, fill = "blue"))


boxplot(fumantes)
boxplot(naofumam, add = T)

mean(fumantes)

mean(naofumam)

```


### Exercício 6
```{r ex6}
ex6 <- c(2, 2, 3, 10, 13, 14, 15, 15, 16, 16, 18, 18, 20, 21, 22, 22, 23, 24, 25, 25, 26, 27, 29, 29, 30, 32, 36, 42,44, 45, 45, 46, 48, 52, 58, 59, 61, 61, 61, 65, 66, 66, 68, 75, 78, 80, 89, 90, 92, 97)

# Histograma e boxplot
```

